name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v2
    - name: make all
      run: make all -C 3_Implementation/
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
